[build-system]
requires = ["setuptools>=69"]
build-backend = "setuptools.build_meta"

[project]
name = "ryvus"
version = "0.1.0"
description = "Ryvus Python SDK"
requires-python = ">=3.10"

dependencies = ["pydantic>=2,<3"]


[tool.setuptools]
packages = ["ryvus"]

[tool.pytest.ini_options]
pythonpath = ["."]
