[package]
name = "ryvus-persistence"
version = "0.1.0"
edition.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true

[dependencies]
ryvus-execution = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
serde = { workspace = true }

[dev-dependencies]
ryvus-executor = { workspace = true }
ryvus-protocol = { workspace = true }
serde_json = { workspace = true }
